add meeting notes for week1 meeting
dedis/d-voting pull request #173
Opened 2022-09-22 13:40 UTC by Flamewind97

Meeting Notes for security auditing 22/09/2022

2022-09-22 13:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dedis/d-voting?pullRequest=173) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dedis/d-voting?pullRequest=173) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dedis/d-voting?pullRequest=173) it.</sub>

2022-09-22 14:35 UTC, nkcr requested changes
Thank you !

Some minor comments:

- Make sure to accept the CLA by clicking on the link (see the [comment](https://github.com/dedis/d-voting/pull/173#issuecomment-1255042192))
- Please name the file `week-1-security-audit.md`.
- Nit pick, but add an empty line after and before titles
- Add the date in the document. This is also a good practice to mention who were present in the meeting.

2022-09-25 13:33 UTC, Flamewind97 commented
> Thank you !
> 
> Some minor comments:
> 
> * Make sure to accept the CLA by clicking on the link (see the [comment](https://github.com/dedis/d-voting/pull/173#issuecomment-1255042192))
> * Please name the file `week-1-security-audit.md`.
> * Nit pick, but add an empty line after and before titles
> * Add the date in the document. This is also a good practice to mention who were present in the meeting.

All the comments have been resolved thanks :)

2022-09-26 09:14 UTC, nkcr approved these changes

2022-09-26 09:14 UTC, merged