Frontend meeting week 2
dedis/d-voting pull request #182
Opened 2022-10-07 08:21 UTC by aelalamy42

The minutes of the meeting of week 2!

2022-10-07 08:33 UTC, nkcr requested changes

2022-10-07 08:51 UTC, aelalamy42 commented
Should be all good now :)

2022-10-07 08:51 UTC, nkcr commented on docs/minutes/week-2-frontend.md
> +Each member of the team has created a PR:
same the the list ; )

2022-10-08 14:33 UTC, aelalamy42 commented
Is it ok now?

2022-10-10 07:28 UTC, nkcr approved these changes

2022-10-10 07:29 UTC, merged