Fix: update db utils script to reflect new architecture
dedis/d-voting pull request #289
Opened 2023-08-02 14:35 UTC by lanterno

The dbUtils script is outdated, and doesn't work with the current backend. I've adjusted the script, and tested it.

Currently, there's no tests, but it might be a good idea later to add some.

Reviewing each commit separately should provide a better idea of the logical sequence of changes.

ToDo:
- [x]  Rename the file to a more sensible name `cli.ts` 
- [x] Use a proper CLI library/tool
- [ ] Add some unit tests (maybe)

closes https://github.com/dedis/d-voting/issues/300

2023-08-02 14:55 UTC, lanterno commented
I was planning to change the JS script into typescript, but apparently, it's a bit more complex to have a CLI in typescript, so I'll do that in another PR.

2023-08-03 13:40 UTC, PascalinDe reviewed
I'm wondering if /src is really the best place... maybe add a directory /src/scripts to make it clear that it's not part of the application code?

apart from that LGTM

2023-08-07 09:27 UTC, lanterno commented
@PascalinDe since it's a small script, I was thinking about renaming it to `cli.ts` in my next PR. 
I think it goes along with the naming for the backend code `server.ts`. 

What do you think?

2023-08-07 09:33 UTC, PascalinDe commented
> @PascalinDe since it's a small script, I was thinking about renaming it to `cli.ts` in my next PR. I think it goes along with the naming for the backend code `server.ts`.
> 
> What do you think?

sounds great!

2023-08-07 09:34 UTC, PascalinDe approved these changes

2023-08-09 09:15 UTC, pierluca commented on web/backend/src/dbUtils.js
> +//   node -e 'require("./src/bUtils").addAdmin("1234")'
```suggestion
//   node -e 'require("./src/dbUtils").addAdmin("1234")'
```

2023-08-09 09:15 UTC, pierluca commented on web/backend/src/dbUtils.js
To add to @PascalinDe 's comments and your suggestion to rename this `cli.js`, I'd like to bring up the NPM convention of having a `bin/` folder and defining it in the `bin` key in the package.json, with a shebang at the top. This would allow the usage of `npx`, which is always nice.

For references:
https://docs.npmjs.com/cli/v9/configuring-npm/package-json#bin
https://blog.shahednasser.com/how-to-create-a-npx-tool/

2023-08-09 09:16 UTC, pierluca commented on web/backend/src/dbUtils.js
Obviously this could be in a follow up PR and not now :-)

2023-08-09 09:23 UTC, PascalinDe submitted a review, later dismissed
now that it is merged, can you update README.docker as well? thanks!

2023-08-09 09:33 UTC, PascalinDe commented
the script is not executing properly in the Docker image:

```
root@40c225d12de8:/web/backend# NODE_PATH=./node_modules node -e 'require("./src/dbUtils").addAdmin("376842")'
/web/backend/src/dbUtils.js:9
import { SequelizeAdapter } from 'casbin-sequelize-adapter';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1197:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at [eval]:1:1
    at Script.runInThisContext (node:vm:122:12)

Node.js v20.5.0
```

I'm not very familiar with JavaScript, maybe it's not meant to be run like this? can you please clarify?

2023-08-11 05:20 UTC, lanterno commented on web/backend/src/dbUtils.js
Check it out.. now it's `npx cli addAdmin --sciper 123`

2023-08-11 05:22 UTC, lanterno commented
@PascalinDe @pierluca I rebased the PR to include the docker changes made by @PascalinDe, and I'm now using a CLI library called CommanderJS to build a CLI. along with npx and node bin, it's a great combination to have a cli tool

example: `npx cli addAdmin --sciper 1234` 

I hope you like it :)

2023-08-16 08:09 UTC, PascalinDe requested changes
can you please update the README.docker as well?

2023-08-16 08:21 UTC, PascalinDe approved these changes

2023-08-16 08:31 UTC, pierluca approved these changes
Very nice ! LGTM

2023-08-16 08:32 UTC, merged