Custom Performance tests
dedis/d-voting pull request #36
Opened 2022-01-17 20:04 UTC by emduc

Provides a basic benchmark, customable in the number of nodes, votes and chunks per ballot.

 The votes being casted are the same vote for all users and contains an empty answer to a text question (full base64-padding).

Implementing a Benchmark required to change the signature of a few methods in the framework of the integrationTest so that they take a more generic type as parameter.

2022-01-18 08:17 UTC, jbsv requested changes
So far looks good, thanks. 
For the long term, can you please add a build in '.github/workflows/go_test.yml' so that this benchmark compiles in CI? The goal is to avoid that any change breaks the benchmark unnoticed.

2022-01-18 09:45 UTC, nkcr commented
Sweet! That's going to be useful. 

The code is still using some ugly `time.Sleep` though. This hack is ok for the integration test, but it doesn't make sense for a benchmark. A proper way of replacing those `time.Sleep` would be to watch for the blockchain: instead of waiting some time for the election to move to the next state for example, we should watch for the block that stores this new state.

I'm gonna try to update the PR.

2022-01-18 10:27 UTC, emduc commented
> So far looks good, thanks. For the long term, can you please add a build in '.github/workflows/go_test.yml' so that this benchmark compiles in CI? The goal is to avoid that any change breaks the benchmark unnoticed.

I added a -bench flag so that the benchmark is also executed in the CI, is that enough or did you mean that I should create a new dedicated yml file ?

2022-01-26 08:21 UTC, jbsv approved these changes

2022-01-26 08:21 UTC, merged